import { describe, expect, test } from '@jest/globals'
import { changePacketHostname } from '../src/common/fake-util'

const clientGameLoadedLog = {
  log: {
    type: 'CLIENT_GAME_LOADED',
    value: {
      attributionId: 'QU+IYXQyoTLwUHuP4WqxJQB2LfBLzxzCIZW4XQGWYOc=',
      ua_launch_id: null,
      lobby_launch_id: 'a4649dc70f0c4c5fb578af37a377a13e',
      typeApp: 'baccarat',
      provider: 'evolution',
      buildId: '6.20240325.123015.40308-372eee56ec',
      userAgent:
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0',
      url: 'https://localhost/frontend/everest/hotfix-release/#category=top_games&game=baccarat&table_id=gwbaccarat000001&lobby_launch_id=a4649dc70f0c4c5fb578af37a377a13e',
      isIframe: false,
      swipeToPlayEnabled: true,
      virtualTableId: '',
      loaderSentLogCount: 1,
      clientTime: 1711632043776,
      browserSupportES2018: true,
      browserSupportES2018RegExp: true,
      browserSupportES2019: true,
      browserSupportES2020: true,
      browserSupportES2021: true,
      browserSupportWebAssembly: true,
      browserSupportWebP: true,
      browserSupportAvif: true,
      browserSupportCurrencyFormat: true,
      browserSupportBigInt: true,
      channel: 'PCMac',
      orientation: 'landscape',
      gameDimensions: { width: 1400, height: 787.5 },
      gameId: '17c0f03dfc679418c95fd203',
    },
  },
}

const clientGameLoadedLogExpect = {
  log: {
    type: 'CLIENT_GAME_LOADED',
    value: {
      attributionId: 'QU+IYXQyoTLwUHuP4WqxJQB2LfBLzxzCIZW4XQGWYOc=',
      ua_launch_id: null,
      lobby_launch_id: 'a4649dc70f0c4c5fb578af37a377a13e',
      typeApp: 'baccarat',
      provider: 'evolution',
      buildId: '6.20240325.123015.40308-372eee56ec',
      userAgent:
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0',
      url: 'https://babylonrd.evo-games.com/frontend/everest/hotfix-release/#category=top_games&game=baccarat&table_id=gwbaccarat000001&lobby_launch_id=a4649dc70f0c4c5fb578af37a377a13e',
      isIframe: false,
      swipeToPlayEnabled: true,
      virtualTableId: '',
      loaderSentLogCount: 1,
      clientTime: 1711632043776,
      browserSupportES2018: true,
      browserSupportES2018RegExp: true,
      browserSupportES2019: true,
      browserSupportES2020: true,
      browserSupportES2021: true,
      browserSupportWebAssembly: true,
      browserSupportWebP: true,
      browserSupportAvif: true,
      browserSupportCurrencyFormat: true,
      browserSupportBigInt: true,
      channel: 'PCMac',
      orientation: 'landscape',
      gameDimensions: { width: 1400, height: 787.5 },
      gameId: '17c0f03dfc679418c95fd203',
    },
  },
}

const clientVideoV2Initialized = {
  log: {
    type: 'CLIENT_VIDEO_V2_INITIALIZED',
    value: {
      device: {
        userAgent:
          'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0',
        screenSize: null,
        type: 'desktop',
        name: null,
        browser: { family: 'Edge', version: '123.0.0.0', forkVersion: '123.0.0.0' },
        os: { family: 'Macosx', version: '10.15.7' },
        threads: 12,
        maxSupportedQuality: null,
      },
      client: { pointInTime: 0, timestamp: 1711632043916 },
      component: { version: '13.52.1_13.20240322.111603_ea7ace73', scenario: null },
      video: { masterHost: 'live1.egcvi.com' },
      session: {
        videoSessionId:
          'rnpua2qz4yxqa3eq-rnpua2qz4yxqa3eqr2ctgr7zsp4a56nb68339801c862bb196f7ac0c93319c87f8964cc99798f8e2a-gwbaccarat000001-af2946',
        gameType: 'baccarat',
        scenario: null,
        referer: 'localhost',
      },
      metrics: {
        wrapperInitToLibLoadingStartedTime: null,
        libLoadingTime: null,
        libLoadedToMountedTime: null,
        isSupportedAudioWorklet: true,
        isSupportedWebP: true,
        isSupportedVideoDecoder: true,
        isSupportedAv1: true,
        isSupportedMseAv1: true,
        isSupportedAudioDecoder: true,
        isSupportedOffscreenCanvas: true,
      },
      v: '13.52.1',
    },
  },
}
const clientVideoV2InitializedExpect = {
  log: {
    type: 'CLIENT_VIDEO_V2_INITIALIZED',
    value: {
      device: {
        userAgent:
          'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0',
        screenSize: null,
        type: 'desktop',
        name: null,
        browser: { family: 'Edge', version: '123.0.0.0', forkVersion: '123.0.0.0' },
        os: { family: 'Macosx', version: '10.15.7' },
        threads: 12,
        maxSupportedQuality: null,
      },
      client: { pointInTime: 0, timestamp: 1711632043916 },
      component: { version: '13.52.1_13.20240322.111603_ea7ace73', scenario: null },
      video: { masterHost: 'live1.egcvi.com' },
      session: {
        videoSessionId:
          'rnpua2qz4yxqa3eq-rnpua2qz4yxqa3eqr2ctgr7zsp4a56nb68339801c862bb196f7ac0c93319c87f8964cc99798f8e2a-gwbaccarat000001-af2946',
        gameType: 'baccarat',
        scenario: null,
        referer: 'babylonrd.evo-games.com',
      },
      metrics: {
        wrapperInitToLibLoadingStartedTime: null,
        libLoadingTime: null,
        libLoadedToMountedTime: null,
        isSupportedAudioWorklet: true,
        isSupportedWebP: true,
        isSupportedVideoDecoder: true,
        isSupportedAv1: true,
        isSupportedMseAv1: true,
        isSupportedAudioDecoder: true,
        isSupportedOffscreenCanvas: true,
      },
      v: '13.52.1',
    },
  },
}

const clientAppLoadingTimeV2 = {
  log: {
    type: 'CLIENT_APP_LOADING_TIME_V2',
    value: {
      version: 14,
      userAgent:
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0',
      game: 'baccarat',
      gameSubType: 'goldenwealth',
      device: 'desktop',
      connectionType: '4g',
      build: '6.20240325.123015.40308-372eee56ec',
      attributionId: 'QU+IYXQyoTLwUHuP4WqxJQB2LfBLzxzCIZW4XQGWYOc=',
      ua_launch_id: null,
      lobby_launch_id: 'a4649dc70f0c4c5fb578af37a377a13e',
      entries: {
        navigation: [
          {
            name: 'https://localhost/frontend/everest/hotfix-release/#category=top_games',
            duration: 124.5,
            initiatorType: 'navigation',
            deliveryType: '',
            nextHopProtocol: 'h3',
            renderBlockingStatus: 'non-blocking',
            fetchStart: 0.9,
            domainLookupStart: 0.9,
            domainLookupEnd: 0.9,
            connectStart: 0.9,
            secureConnectionStart: 0.9,
            connectEnd: 0.9,
            requestStart: 2.5,
            responseStart: 81.8,
            responseEnd: 107.2,
            transferSize: 54425,
            encodedBodySize: 54125,
            decodedBodySize: 204671,
            responseStatus: 200,
            domInteractive: 121.3,
            domContentLoadedEventStart: 121.3,
            domContentLoadedEventEnd: 121.3,
            domComplete: 124.5,
            loadEventStart: 124.5,
            loadEventEnd: 124.5,
            type: 'navigate',
          },
        ],
        'visibility-state': [{ name: 'visible' }],
        paint: [
          { name: 'first-paint', startTime: 474.6 },
          { name: 'first-contentful-paint', startTime: 796.7 },
        ],
        resource: [
          {
            name: 'https://live1.egcvi.com/cdn/app/30/amlst:gwr1_bi_auto/manifest-ws2.json?videoSessionId=***&videoToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnd3IxX2IiLCJleHAiOjE3MTE3MTg0MzksImlzcyI6IkwxeTZxcmVOTFMifQ.cgAtJI7urv4GF_2ucVZNi4tUBuG5A0VuCjj-vIFN60c&noredirect=1&streamid=0&ac=aac&vc=h264',
            startTime: 322420.7,
            duration: 439.7,
            initiatorType: 'xmlhttprequest',
            deliveryType: '',
            nextHopProtocol: '',
            renderBlockingStatus: 'non-blocking',
            fetchStart: 322420.7,
            responseEnd: 322860.4,
            transferSize: 0,
          },
          {
            name: 'https://localhost/config?table_id=gwbaccarat000001&origin=https%3A%2F%2Fbabylonrd.evo-games.com&client_version=6.20240325.123015.40308-372eee56ec',
            startTime: 323677.6,
            duration: 1109.9,
            initiatorType: 'fetch',
            deliveryType: '',
            nextHopProtocol: 'h3',
            renderBlockingStatus: 'non-blocking',
            fetchStart: 323677.6,
            domainLookupStart: 323678.7,
            domainLookupEnd: 323678.7,
            connectStart: 323678.7,
            secureConnectionStart: 323678.9,
            connectEnd: 323754.6,
            requestStart: 323754.7,
            responseStart: 324787.1,
            responseEnd: 324787.5,
            transferSize: 3627,
            encodedBodySize: 3327,
            decodedBodySize: 8055,
            responseStatus: 200,
          },
          {
            name: 'https://localhost/log?client_version=6.20240325.123015.40308-372eee56ec',
            startTime: 323678,
            duration: 1088.2,
            initiatorType: 'beacon',
            deliveryType: '',
            nextHopProtocol: 'h3',
            renderBlockingStatus: 'non-blocking',
            fetchStart: 323678,
            domainLookupStart: 323678,
            domainLookupEnd: 323678,
            connectStart: 323678,
            secureConnectionStart: 323678,
            connectEnd: 323678,
            requestStart: 323754.9,
            responseStart: 324765.7,
            responseEnd: 324766.2,
            transferSize: 304,
            encodedBodySize: 4,
            decodedBodySize: 4,
            responseStatus: 200,
          },
          {
            name: 'https://static.egcdn.com/frontend/gametech/sounds/baccarat-goldenwealth/ecasOptions.json',
            startTime: 324792,
            duration: 528.3,
            initiatorType: 'fetch',
            deliveryType: '',
            nextHopProtocol: '',
            renderBlockingStatus: 'non-blocking',
            fetchStart: 324792,
            responseEnd: 325320.3,
            transferSize: 0,
            responseStatus: 200,
          },
          {
            name: 'https://bshots.egcvi.com/thumbnail/gwr1_bs_med_M.jpg',
            startTime: 325332.2,
            duration: 78.4,
            initiatorType: 'fetch',
            deliveryType: '',
            nextHopProtocol: '',
            renderBlockingStatus: 'non-blocking',
            fetchStart: 325332.2,
            responseEnd: 325410.6,
            transferSize: 0,
            responseStatus: 200,
          },
          {
            name: 'https://localhost/api/snapshot?casinoId=babylonrd0000001&currency=KRW&extPlayerId=tttaa22&tableId=gwbaccarat000001&country=KR&client_version=6.20240325.123015.40308-372eee56ec',
            startTime: 325338.3,
            duration: 997.6,
            initiatorType: 'fetch',
            deliveryType: '',
            nextHopProtocol: 'h3',
            renderBlockingStatus: 'non-blocking',
            fetchStart: 325338.3,
            domainLookupStart: 325338.3,
            domainLookupEnd: 325338.3,
            connectStart: 325338.3,
            secureConnectionStart: 325338.3,
            connectEnd: 325338.3,
            requestStart: 325339.1,
            responseStart: 326335.6,
            responseEnd: 326335.9,
            transferSize: 300,
            responseStatus: 204,
          },
          {
            name: 'https://localhost/api/player/screenName?client_version=6.20240325.123015.40308-372eee56ec',
            startTime: 325339.3,
            duration: 1010.5,
            initiatorType: 'fetch',
            deliveryType: '',
            nextHopProtocol: 'h3',
            renderBlockingStatus: 'non-blocking',
            fetchStart: 325339.3,
            domainLookupStart: 325339.3,
            domainLookupEnd: 325339.3,
            connectStart: 325339.3,
            secureConnectionStart: 325339.3,
            connectEnd: 325339.3,
            requestStart: 325339.7,
            responseStart: 326349.5,
            responseEnd: 326349.8,
            transferSize: 321,
            encodedBodySize: 21,
            decodedBodySize: 21,
            responseStatus: 200,
          },
          {
            name: 'https://seoa-mdp-e03.egcvi.com/app/30/amlst:gwr1_bi_auto/manifest-ws2.json?ac=aac&streamid=0&vc=h264&videoSessionId=***&videoToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnd3IxX2IiLCJleHAiOjE3MTE3MTg0NDQsImlzcyI6IkwxeTZxcmVOTFMifQ.O5rRsoqB4qQKTeu5JLZ6UTuOBNWkX6BGTjLsa64cncc',
            startTime: 327221,
            duration: 237.4,
            initiatorType: 'xmlhttprequest',
            deliveryType: '',
            nextHopProtocol: '',
            renderBlockingStatus: 'non-blocking',
            fetchStart: 327221,
            responseEnd: 327458.4,
            transferSize: 0,
            responseStatus: 200,
          },
        ],
        'first-input': [
          {
            name: 'pointerdown',
            startTime: 322614.8,
            duration: 32,
            processingStart: 322616.2,
            processingEnd: 322616.4,
            cancelable: true,
          },
        ],
        mark: [
          { name: 'evoAppSwitchStarted', startTime: 322826.7 },
          { name: 'evoLoaderClosed', startTime: 326900.3 },
          { name: 'evoVideoComponentMounted', startTime: 327042.1 },
          { name: 'evoVideoPlaying', startTime: 329457.7 },
          { name: '_evoReportGenerated', startTime: 341906.3 },
        ],
        'long-animation-frame': [
          {
            name: 'long-animation-frame',
            startTime: 326073.9,
            duration: 147,
            blockingDuration: 97,
            scripts: [
              {
                name: 'script',
                entryType: 'script',
                startTime: 326074,
                duration: 147,
                invoker:
                  'IMG[src=https://static.egcdn.com/frontend/everest/hotfix-release/images/cards.1452a14b.jpg].onload',
                invokerType: 'event-listener',
                windowAttribution: 'self',
                executionStart: 326074,
                sourceURL: '',
                sourceFunctionName: '',
                sourceCharPosition: -1,
              },
            ],
          },
        ],
      },
      evoAppSwitchStarted: 322826.7,
      evoLoaderClosed: 4073.6,
      evoVideoComponentMounted: 4215.4,
      evoVideoPlaying: 6631,
    },
  },
}
const clientAppLoadingTimeV2Expect = {
  log: {
    type: 'CLIENT_APP_LOADING_TIME_V2',
    value: {
      version: 14,
      userAgent:
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0',
      game: 'baccarat',
      gameSubType: 'goldenwealth',
      device: 'desktop',
      connectionType: '4g',
      build: '6.20240325.123015.40308-372eee56ec',
      attributionId: 'QU+IYXQyoTLwUHuP4WqxJQB2LfBLzxzCIZW4XQGWYOc=',
      ua_launch_id: null,
      lobby_launch_id: 'a4649dc70f0c4c5fb578af37a377a13e',
      entries: {
        navigation: [
          {
            name: 'https://babylonrd.evo-games.com/frontend/everest/hotfix-release/#category=top_games',
            duration: 124.5,
            initiatorType: 'navigation',
            deliveryType: '',
            nextHopProtocol: 'h3',
            renderBlockingStatus: 'non-blocking',
            fetchStart: 0.9,
            domainLookupStart: 0.9,
            domainLookupEnd: 0.9,
            connectStart: 0.9,
            secureConnectionStart: 0.9,
            connectEnd: 0.9,
            requestStart: 2.5,
            responseStart: 81.8,
            responseEnd: 107.2,
            transferSize: 54425,
            encodedBodySize: 54125,
            decodedBodySize: 204671,
            responseStatus: 200,
            domInteractive: 121.3,
            domContentLoadedEventStart: 121.3,
            domContentLoadedEventEnd: 121.3,
            domComplete: 124.5,
            loadEventStart: 124.5,
            loadEventEnd: 124.5,
            type: 'navigate',
          },
        ],
        'visibility-state': [{ name: 'visible' }],
        paint: [
          { name: 'first-paint', startTime: 474.6 },
          { name: 'first-contentful-paint', startTime: 796.7 },
        ],
        resource: [
          {
            name: 'https://live1.egcvi.com/cdn/app/30/amlst:gwr1_bi_auto/manifest-ws2.json?videoSessionId=***&videoToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnd3IxX2IiLCJleHAiOjE3MTE3MTg0MzksImlzcyI6IkwxeTZxcmVOTFMifQ.cgAtJI7urv4GF_2ucVZNi4tUBuG5A0VuCjj-vIFN60c&noredirect=1&streamid=0&ac=aac&vc=h264',
            startTime: 322420.7,
            duration: 439.7,
            initiatorType: 'xmlhttprequest',
            deliveryType: '',
            nextHopProtocol: '',
            renderBlockingStatus: 'non-blocking',
            fetchStart: 322420.7,
            responseEnd: 322860.4,
            transferSize: 0,
          },
          {
            name: 'https://babylonrd.evo-games.com/config?table_id=gwbaccarat000001&origin=https%3A%2F%2Fbabylonrd.evo-games.com&client_version=6.20240325.123015.40308-372eee56ec',
            startTime: 323677.6,
            duration: 1109.9,
            initiatorType: 'fetch',
            deliveryType: '',
            nextHopProtocol: 'h3',
            renderBlockingStatus: 'non-blocking',
            fetchStart: 323677.6,
            domainLookupStart: 323678.7,
            domainLookupEnd: 323678.7,
            connectStart: 323678.7,
            secureConnectionStart: 323678.9,
            connectEnd: 323754.6,
            requestStart: 323754.7,
            responseStart: 324787.1,
            responseEnd: 324787.5,
            transferSize: 3627,
            encodedBodySize: 3327,
            decodedBodySize: 8055,
            responseStatus: 200,
          },
          {
            name: 'https://babylonrd.evo-games.com/log?client_version=6.20240325.123015.40308-372eee56ec',
            startTime: 323678,
            duration: 1088.2,
            initiatorType: 'beacon',
            deliveryType: '',
            nextHopProtocol: 'h3',
            renderBlockingStatus: 'non-blocking',
            fetchStart: 323678,
            domainLookupStart: 323678,
            domainLookupEnd: 323678,
            connectStart: 323678,
            secureConnectionStart: 323678,
            connectEnd: 323678,
            requestStart: 323754.9,
            responseStart: 324765.7,
            responseEnd: 324766.2,
            transferSize: 304,
            encodedBodySize: 4,
            decodedBodySize: 4,
            responseStatus: 200,
          },
          {
            name: 'https://static.egcdn.com/frontend/gametech/sounds/baccarat-goldenwealth/ecasOptions.json',
            startTime: 324792,
            duration: 528.3,
            initiatorType: 'fetch',
            deliveryType: '',
            nextHopProtocol: '',
            renderBlockingStatus: 'non-blocking',
            fetchStart: 324792,
            responseEnd: 325320.3,
            transferSize: 0,
            responseStatus: 200,
          },
          {
            name: 'https://bshots.egcvi.com/thumbnail/gwr1_bs_med_M.jpg',
            startTime: 325332.2,
            duration: 78.4,
            initiatorType: 'fetch',
            deliveryType: '',
            nextHopProtocol: '',
            renderBlockingStatus: 'non-blocking',
            fetchStart: 325332.2,
            responseEnd: 325410.6,
            transferSize: 0,
            responseStatus: 200,
          },
          {
            name: 'https://babylonrd.evo-games.com/api/snapshot?casinoId=babylonrd0000001&currency=KRW&extPlayerId=tttaa22&tableId=gwbaccarat000001&country=KR&client_version=6.20240325.123015.40308-372eee56ec',
            startTime: 325338.3,
            duration: 997.6,
            initiatorType: 'fetch',
            deliveryType: '',
            nextHopProtocol: 'h3',
            renderBlockingStatus: 'non-blocking',
            fetchStart: 325338.3,
            domainLookupStart: 325338.3,
            domainLookupEnd: 325338.3,
            connectStart: 325338.3,
            secureConnectionStart: 325338.3,
            connectEnd: 325338.3,
            requestStart: 325339.1,
            responseStart: 326335.6,
            responseEnd: 326335.9,
            transferSize: 300,
            responseStatus: 204,
          },
          {
            name: 'https://babylonrd.evo-games.com/api/player/screenName?client_version=6.20240325.123015.40308-372eee56ec',
            startTime: 325339.3,
            duration: 1010.5,
            initiatorType: 'fetch',
            deliveryType: '',
            nextHopProtocol: 'h3',
            renderBlockingStatus: 'non-blocking',
            fetchStart: 325339.3,
            domainLookupStart: 325339.3,
            domainLookupEnd: 325339.3,
            connectStart: 325339.3,
            secureConnectionStart: 325339.3,
            connectEnd: 325339.3,
            requestStart: 325339.7,
            responseStart: 326349.5,
            responseEnd: 326349.8,
            transferSize: 321,
            encodedBodySize: 21,
            decodedBodySize: 21,
            responseStatus: 200,
          },
          {
            name: 'https://seoa-mdp-e03.egcvi.com/app/30/amlst:gwr1_bi_auto/manifest-ws2.json?ac=aac&streamid=0&vc=h264&videoSessionId=***&videoToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnd3IxX2IiLCJleHAiOjE3MTE3MTg0NDQsImlzcyI6IkwxeTZxcmVOTFMifQ.O5rRsoqB4qQKTeu5JLZ6UTuOBNWkX6BGTjLsa64cncc',
            startTime: 327221,
            duration: 237.4,
            initiatorType: 'xmlhttprequest',
            deliveryType: '',
            nextHopProtocol: '',
            renderBlockingStatus: 'non-blocking',
            fetchStart: 327221,
            responseEnd: 327458.4,
            transferSize: 0,
            responseStatus: 200,
          },
        ],
        'first-input': [
          {
            name: 'pointerdown',
            startTime: 322614.8,
            duration: 32,
            processingStart: 322616.2,
            processingEnd: 322616.4,
            cancelable: true,
          },
        ],
        mark: [
          { name: 'evoAppSwitchStarted', startTime: 322826.7 },
          { name: 'evoLoaderClosed', startTime: 326900.3 },
          { name: 'evoVideoComponentMounted', startTime: 327042.1 },
          { name: 'evoVideoPlaying', startTime: 329457.7 },
          { name: '_evoReportGenerated', startTime: 341906.3 },
        ],
        'long-animation-frame': [
          {
            name: 'long-animation-frame',
            startTime: 326073.9,
            duration: 147,
            blockingDuration: 97,
            scripts: [
              {
                name: 'script',
                entryType: 'script',
                startTime: 326074,
                duration: 147,
                invoker:
                  'IMG[src=https://static.egcdn.com/frontend/everest/hotfix-release/images/cards.1452a14b.jpg].onload',
                invokerType: 'event-listener',
                windowAttribution: 'self',
                executionStart: 326074,
                sourceURL: '',
                sourceFunctionName: '',
                sourceCharPosition: -1,
              },
            ],
          },
        ],
      },
      evoAppSwitchStarted: 322826.7,
      evoLoaderClosed: 4073.6,
      evoVideoComponentMounted: 4215.4,
      evoVideoPlaying: 6631,
    },
  },
}

const evolutionUrl = new URL('https://babylonrd.evo-games.com/frontend/everest/hotfix-release/#category=top_games')

describe('websocket baccarat url test', () => {
  test('clientGameLoadedLog test', async () => {
    const packet = clientGameLoadedLog

    changePacketHostname(packet, evolutionUrl.hostname)

    expect(packet).toStrictEqual(clientGameLoadedLogExpect)

    console.log('end')
  })
  test('clientVideoV2Initialized test', async () => {
    const packet = clientVideoV2Initialized

    changePacketHostname(packet, evolutionUrl.hostname)

    expect(packet).toStrictEqual(clientVideoV2InitializedExpect)

    console.log('end')
  })
  test('clientAppLoadingTimeV2 test', async () => {
    const packet = clientAppLoadingTimeV2

    changePacketHostname(packet, evolutionUrl.hostname)

    expect(packet).toStrictEqual(clientAppLoadingTimeV2Expect)

    console.log('end')
  })
})
