#! /bin/bash
BASEDIR=$(dirname $0)
cd $BASEDIR
#aws codebuild list-builds-for-project --region ap-northeast-1 --profile faker --project-name "build-fake-korea"
# AWS CodeBuild 프로젝트 이름을 입력받음
PROJECT_NAME=build-fake-korea

# 프로젝트 이름이 입력되지 않았을 경우 오류 메시지 출력
if [ -z "$PROJECT_NAME" ]; then
  echo "Usage: $0 <project-name>"
  exit 1
fi

# 최신 빌드 ID 한 개 가져오기
echo "Fetching the latest build for project: $PROJECT_NAME"
LATEST_BUILD_ID=$(aws codebuild list-builds-for-project --region ap-northeast-1 --profile faker --project-name $PROJECT_NAME --max-items 1 --sort-order DESCENDING --query 'ids[0]' --output text)

# 빌드 ID가 없을 경우 처리
if [ -z "$LATEST_BUILD_ID" ] || [ "$LATEST_BUILD_ID" == "None" ]; then
  echo "No builds found for project: $PROJECT_NAME"
  exit 0
fi

# 가져온 빌드 ID 출력하고 해당 빌드의 상세 정보 확인
echo "Latest Build ID: $LATEST_BUILD_ID"
echo "Fetching build details..."

echo "aws codebuild batch-get-builds --region ap-northeast-1 --profile faker --ids $LATEST_BUILD_ID"

# 빌드 ID의 상세 정보 가져오기
aws codebuild batch-get-builds --region ap-northeast-1 --profile faker --ids $LATEST_BUILD_ID $LATEST_BUILD_ID

exit 0
