#! /bin/bash
BASEDIR=$(dirname $0)
cd $BASEDIR

clusterId=fake-task
serviceName=fake-resolver-srv
regionName=ap-northeast-1

aws ecs update-service --cluster $clusterId --service $serviceName --region $regionName --force-new-deployment --profile faker