#! /bin/bash
BASEDIR=$(dirname $0)
cd $BASEDIR

clusterId=fake-token-generator
serviceName=fake-token-generator-srv
regionName=ap-northeast-1

aws ecs update-service --cluster $clusterId --service $serviceName --region $regionName --force-new-deployment --profile faker