#! /bin/bash
BASEDIR=$(dirname $0)
cd $BASEDIR

clusterId=fake-api-blue
serviceName=fake-api-node-blue-srv
regionName=ap-northeast-2

aws ecs update-service --cluster $clusterId --service $serviceName --region $regionName --force-new-deployment --profile faker